name: Waka Readme

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 21 * * *"

jobs:
  waka-time:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master # this action name
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          commit_message: "Updated waka-readme graph with new metrics"
          TIME_RANGE: last_30_days
          LANG_COUNT: 4
          CODE_LANG: Python,YAML
          
